[package]
name = "udith"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bstr = "1"
fluent-uri = "0.1"
nom = "7"
ouroboros = "0.18"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net",
] }
